name: CI

on:
  push:
    branches:
      - master
  pull_request:
    ranches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies
        run: yarn

      - name: Check tests
        run: yarn test --coverage

      - name: Check linting
        run: yarn lint

      - name: Check commit message
        uses: wagoid/commitlint-github-action@v2
